
name: Python_Mac_Compiler
run-name: comping Tape on - ${{runner.os}} 
on:
  workflow_dispatch:

jobs:
  mac_compiler:
    runs-on: macos-
    steps:
      - name: cloner
        uses: actions/checkout@v5
        with:
          ref: "PyWebview_version"
      - name: list files
        run: ls ${{ github.workspace }}
    
